language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt-get update -qq
  # Boost
  - sudo apt-get install libboost-all-dev 
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
  - xvfb

script: 
  - ./download_other_githubs
  - qmake plane_test_console.pro
  - make --silent debug
  - ./plane_test_console
  #- qmake plane_test_apfloat.pro
  #- make debug
  # Codecov
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint
