language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

# Xenial
services:
  - xvfb

script: 
  - ./download_other_githubs
  - qmake plane_test_console.pro
  - make debug
  - ./plane_test_console
  #- qmake plane_test_apfloat.pro
  #- make debug
  # Codecov
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint